name: build-idf

on:
  push:
    paths:
      - "components/**"
      - "mesh_node/**"
      - "mesh_root/**"
      - ".github/workflows/build-idf.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - { name: mesh_node, path: "mesh_node" }
          - { name: mesh_root, path: "mesh_root" }
    container:
      image: espressif/idf:v5.2.1
      options: --user 0
    steps:
      - uses: actions/checkout@v4

      # IMPORTANT: source the IDF environment before using idf.py
      - name: Build ${{ matrix.app.name }}
        shell: bash
        run: |
          set -e
          . /opt/esp/idf/export.sh
          cd "${{ matrix.app.path }}"
          idf.py --version
          idf.py set-target esp32s3
          idf.py build
